/** OOPSBannerApp UC2 - OOPS Banner Display ApplicationException
*
* This class demonstrates the creation of a visual banner displaying the word "OOPS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the 
* console using individual print statement for each line, creating a decorative
* text effect.
* 
* <p>The banner is generated by printing predefined string patterns line by line,
* where each line contributes to forming the letters O,O,P and S in a stylized format.
* This extends a basic user story by adding visual presentation to a simple message output.
* </p>

* @author Developer
* @version 2.0
*/

class PrintOOPS{
	public static void main(String[] args){		
		
		System.out.println("   ***   " + " " +"   ***   " + " " + "******   " + " " + "   ***** ");
		System.out.println(" **   ** " + " " +" **   ** " + " " + "**    ** " + " " + " **      ");
		System.out.println("**     **" + " " +"**     **" + " " + "**     **" + " " + "**       ");
		System.out.println("**     **" + " " +"**     **" + " " + "**    ** " + " " + " **     ");
		System.out.println("**     **" + " " +"**     **" + " " + "******   " + " " + "   ***   ");
		System.out.println("**     **" + " " +"**     **" + " " + "**       " + " " + "      ** ");
		System.out.println("**     **" + " " +"**     **" + " " + "**       " + " " + "       **");
		System.out.println(" **   ** " + " " +" **   ** " + " " + "**       " + " " + "      ** ");
		System.out.println("   ***   " + " " +"   ***   " + " " + "**       " + " " + " *****   ");
	}
}